version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      target: development
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=https://api.tms-applications.com

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:80"
    command: /start-reload.sh
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # Mount initialization scripts
    environment:
      MYSQL_DATABASE: tms_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3036:3306"

volumes:
  mysql_data:
